### ISSUE TITLE
New patch

### ISSUE THREAD

**Issue by justscribe** [NightlyRevenger/TataruHelper#10]
**Describe the bug**
After the new patch it didn't work.

**To Reproduce**
1. Start app.
2. Chat window appears.
3. App found the process.
4. But the window always is empty.

**Expected behavior**
Window must be with the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/8200485/74773602-d7f7bd80-529a-11ea-8267-3dd4870491b6.png)
![image](https://user-images.githubusercontent.com/8200485/74774004-a4696300-529b-11ea-9583-e9fd509cdfc9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Version [0.9.63.0]

**Comment by xDarkOne** [comment]
[https://github.com/NightlyRevenger/TataruHelper/releases/latest](Fixed)
