### ISSUE TITLE
Option to disable auto switch Translation Engine 

### ISSUE THREAD

**Issue by InitialDet** [NightlyRevenger/TataruHelper#11]
It would be nice if it could retry some times, instead of switching to another translation engine when some error happens.

Every time it is switching from Google Translator to DeepL, which basically makes every translation lose any sense (in Portuguese at least) . I would love if I had the option to only use Google Translator.

**Comment by ivantey** [comment]
I also often switch language
can I make an option so that the language does not switch, and if the attempt is unsuccessful, a request is made again and this is written to the window with the dialog?
