### ISSUE TITLE
User config will be cleared when shut down computer without exit TataruHelper

### ISSUE THREAD

**Issue by Echoring** [NightlyRevenger/TataruHelper#20]
**Describe the bug**
I shutdown my computer while forget to exit TataruHelper.
When I start TataruHelper again tomorrow, I find that all user config are gone.
(I do not mean change not saved. it has been modified and saved long time ago and not been modified that day.)
This has happen twice.

**To Reproduce**
1. Start TataruHelper
2. Change user config as you like
3. Reboot computer without exit TataruHelper
4. Start TataruHelper again and find that all is gone.

**Expected behavior**
Config will not be cleared when shut down computer without exit TataruHelper
(Change not saved for this time is OK, but don't clear all config I changed before)

**Desktop (please complete the following information):**
 - OS: Windows 10 X64

**Comment by xDarkOne** [comment]
Thank you for the information! We will look into this issue.

**Comment by Echoring** [comment]
Oh, sorry for giving wrong issue!
I meet this problem again and finally find out that it's not because of unnormal exit, but hotkey conflict that makes this issue.
If a software has registered a hotkey which TataruHelper config want to register, TataruHelper will meet an error and skip this config, causing bug above.
