### ISSUE TITLE
Tataru isnt showing

### ISSUE THREAD

**Issue by tuskinhu** [NightlyRevenger/TataruHelper#24]
After a normal install, run FFXIV, swap to windows, run tataru, I see the translation square, but when I return to FFXIV, the square vanishes, if I come back to Tataro, i see some translations if click "show chat window", but every time I swap back to FFXIV, chat window vanishes. I do have marked "Always on top" flag.

Is there any other config that a have to make in game or windows, thus that on log, to make tataro dont close chat window?

**Comment by xDarkOne** [comment]
You should enable borderless in FFXIV settings.

**Comment by tuskinhu** [comment]
Thank you, worked!
