### ISSUE TITLE
SE changed signatures again after patch 6.01

### ISSUE THREAD

**Issue by winw1010** [NightlyRevenger/TataruHelper#37]
The latest signatures of DIALOGPANEL and CUTSCENE are not valid anymore.
However, DIALOGPANEL can be restored by using 5.5's signatures file.

**Comment by xDarkOne** [comment]
We will fix it as soon as possible

**Comment by winw1010** [comment]
Thank you. :)

**Comment by winw1010** [comment]
Thank you for update :D
