### ISSUE TITLE
Is there any software similar to this that can work on any other video game?

### ISSUE THREAD

**Issue by dkaerit** [NightlyRevenger/TataruHelper#51]
**Is your feature request related to a problem? Please describe.**
I wish I could translate other games like Lost Sphear but I don't think there are any tools that do a function like this with FFXIV.  

**Describe the solution you'd like**
I think it would be interesting to expand its compatibility with other videogames, although I don't know how viable it might be.

**Comment by GitTotsu** [comment]
This is just a dialog translator, it captures the NPC dialog that is sent to the game chat and displays it in the software dialog box. Each game works in a different way, so there is no such thing as a global translator unless you adapt it for each game (which is absurd to think about).

**Comment by Hardivh** [comment]
Yup, I'd like some software to translate Crisis Core (it doesn't have portuguese) and was wondering if there was any kind of program that can do it
